CONFIG = {
    "excelfile": "BAC-GF Systems - Jun23.xlsx",
    "modified_excelfile": "out/GFG Systems_modified.xlsx",
    "sheetname_source": "All Services",
    "sheetname_dest": "Template",
    "sysname_col": 0,
    "sysname_col_append": " Service",
    "start_row": 3,
    "max_title_chars": 30,
    "field_mapping": {
        "D2": "A",
        "E5": "F",
        "C8": ["E", "F", "G", "I"],
        "H11": "K",
        "H8": "L",
        "J8": ["S", "T", "U", "V"],
        "D16": "AB",
        "D20": "AE",
        "H16": "AF",
        "H20": "AG",
        "Q8": "AH",
        "Q18": "AJ",
    },
    "pre_fills": {
        "H8": "BHD ",
    },
    "short_titles": {
        "ISO 27001:2013 Recertification Audit": "ISO 27001",
    },
}
